### ISSUE TITLE
Rasa App not sending images to livechat

### ISSUE THREAD

**Issue by thecion** [RocketChat/Apps.Rasa#38]
Hello ppl, I'm having a problem trying to work with images in livechat through RasaApp.

This appears to be happening only when using a Rasa Bot with RasaApp, since I can send images to the user by myself and the user can reply with another image during a "normal" conversation.

Testing:

* I have an utter for the images setup like this in my domain.yml:
```
utter_explica_numprocesso:
  - image: https://s.conjur.com.br/img/b/tabela-numeracao.jpeg
    text: É um número grande, conforme esta imagem.
  - image: https://s.conjur.com.br/img/b/tabela-numeracao.jpeg
    text: É um número grande, conforme essa imagem. Mas ele é fundamental. Vamos lá?
```

* Images are working fine if I use the Integration menu (Administration -> Integration), in which I have set up an outgoing webhook for communicating with the Rasa Server. Below a screenshot of a Rasa Bot sending an Image to the user inside RocketChat, via integration webhook:

![01_image_rocketchat](https://user-images.githubusercontent.com/74257216/124133932-b1ce5a00-da58-11eb-853b-2396278b3f9b.png)

* However the same utter does not work with livechat and RasaApp, as shown in the screenshot below

![02_image_livechat](https://user-images.githubusercontent.com/74257216/124134882-ae879e00-da59-11eb-9473-5c81dca92d8a.png)

* The image is not shown as well in the omnichannel chat log:

![03_livechat_rocketview](https://user-images.githubusercontent.com/74257216/124135134-e989d180-da59-11eb-96a2-bb6114294453.png)

My questions are:

1. Should RasaApp work with linked images?
2. If not, how should I send files to the App API POST incoming?

Best regards.
